Feature add metric handling
freepik-company/telephponic pull request #16
Opened 2023-11-14 15:39 UTC by Muriano

2023-11-15 14:08 UTC, kerunaru requested changes

2023-11-15 14:08 UTC, kerunaru commented on composer.json
> +    "ext-redis": "*",
No sé si te acuerdas pero dejamos esto como opcional porque hay proyectos que pueden tener o no necesidad de cada una de las integraciones.

Estas tres, están como sugeridas en la sección `suggest` y, además, cada integración hace una llamada a `extension_loaded` para arrojar una excepción en caso de querer usarla y no tener el módulo de PHP instalado.

2023-11-27 09:08 UTC, Muriano commented on composer.json
> +    "ext-redis": "*",
solucionado.

2023-11-27 09:10 UTC, kerunaru approved these changes

2023-11-27 09:34 UTC, merged